// Copyright (c) to owners found in https://github.com/arlm/WinApi/blob/master/COPYRIGHT.md. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.IsAnyCPUManagedDll(System.String)~System.Nullable{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.IsUnmanagedDll64Bit(System.String)~System.Nullable{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.IsManagedDll(System.String)~System.Nullable{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.Is64BitManagedDll(System.String)~System.Nullable{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.Is32BitManagedDll(System.String)~System.Nullable{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.GetDllMachineType(System.String)~WinApi.PeCoff.IMAGE_FILE_HEADER")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:WinApi.PeCoff.PeCoffFiles.IsDebugDLL(System.String,System.Boolean@)~System.Nullable{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#IsDebugDLL(System.String,System.Boolean&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#IsUnmanagedDll64Bit(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#IsManagedDll(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#IsAnyCPUManagedDll(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#Is64BitManagedDll(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#Is32BitManagedDll(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "WinApi.PeCoff.PeCoffFiles.#GetDllMachineType(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_SECTION_HEADER.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_DATA_DIRECTORY.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_COR20_HEADER.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_RESOURCE_DATA_ENTRY.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_RESOURCE_DIRECTORY_ENTRY.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_RESOURCE_DIRECTORY.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_FILE_HEADER.GetHashCode~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0025:Non-readonly field referenced in 'GetHashCode()'", Justification = "Applying Mercene Primes as base to XOR'ing the fields HashCodes", Scope = "member", Target = "~M:WinApi.PeCoff.IMAGE_DOS_HEADER.GetHashCode~System.Int32")]

